default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample3_development
test:
  <<: *default
  database: sample3_test

production:
  <<: *default
  database: sample3_production
  username: sample3
  password: <%= ENV['SAMPLE3_DATABASE_PASSWORD'] %>
